import { Geist, Geist_Mono, Gloock, Mate_SC, Moderustic } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gloock = Gloock({
  variable: "--font-gloock",
  subsets: ["latin"],
  weight:"400",
});

const mateSC = Mate_SC({
  variable: "--font-mate-sc",
  subsets: ["latin"],
  weight:"400", 
});

const moderustic= Moderustic({
   variable: "--font-moderustic",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} 
                  ${geistMono.variable}
                  ${gloock.variable}
                  ${mateSC.variable}
                  ${moderustic.variable}
                   h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
